In [1]:
l = [1, 2, 3, 's', 1.2]
print(type(l))

<class 'list'>


In [2]:
b = 'Monthy Python'
l = [1, 2, ['a', b]]

In [3]:
l

[1, 2, ['a', 'Monthy Python']]

In [4]:
l.reverse()
l

[['a', 'Monthy Python'], 2, 1]

In [5]:
l = ['f', 'a', 'z', 't']
l.sort()
l

['a', 'f', 't', 'z']

In [6]:
for element in l:
    print(element)

a
f
t
z


In [7]:
start = 10
stop = 20 #20 is not included
step = 2
list(range(start, stop, step)) # 'start is included in the list but 'stop' in not ! 

[10, 12, 14, 16, 18]

In [8]:
list(range(10)) # with one integer input parameter you'll get a list from zero to 'stop' with an increment valae of 1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
l1 = [] # instantiate an empty list
l1.append(1)
l1.append('a')
l1.append(1.2)
l1

[1, 'a', 1.2]

In [11]:
import numpy as np
l2 = ['Python', 15, np.random.rand(2,2)] 
# np.random.rand(2,2) creates a 2x2 matrix with random numbers in the [0,1] interval in its elements
l2

['Python',
 15,
 array([[0.4164039 , 0.00418287],
        [0.54906471, 0.64949663]])]

In [12]:
l = l1 + l2 # concatenate the two lists
l

[1,
 'a',
 1.2,
 'Python',
 15,
 array([[0.4164039 , 0.00418287],
        [0.54906471, 0.64949663]])]

In [13]:
len(l) # length

6

In [14]:
l[1:4]

['a', 1.2, 'Python']

In [15]:
l[-1] # the last element is indexed as -1

array([[0.4164039 , 0.00418287],
       [0.54906471, 0.64949663]])

In [16]:
l.remove('a') # remove a particular item
l

[1,
 1.2,
 'Python',
 15,
 array([[0.4164039 , 0.00418287],
        [0.54906471, 0.64949663]])]

In [17]:
del l[2] # delete an item at a given position
print(l)

[1, 1.2, 15, array([[0.4164039 , 0.00418287],
       [0.54906471, 0.64949663]])]


In [18]:
l = ['Monty', 'Python']
print(''.join(l))
print(' '.join(l))
print(', '.join(l))

MontyPython
Monty Python
Monty, Python


In [19]:
database = 'SALES'
table = 'WEBSHOP_SALES'
month = 'April'
day = ['20', '21', '22'] # since it is an input to a string function (the 'join()' method, list elements can only be strings! 

query = f"""
SELECT *
FROM {database}.{table}
WHERE month = '{month}'
AND day IN ({", ".join(day)})
"""

# note paranthesis (needed for the proper SQL syntax) and the curly braces (for the f-string) after the IN clause

print(query)


SELECT *
FROM SALES.WEBSHOP_SALES
WHERE month = 'April'
AND day IN (20, 21, 22)



### Dictionaries

In [20]:
class_size = {
    'Java': 20,
    'C++': 23, 
    'Python': 29
}

print(type(class_size))
print(class_size)

<class 'dict'>
{'Java': 20, 'C++': 23, 'Python': 29}


In [21]:
for key, value in class_size.items():
    print('The number of students in the', key, 'class is', value, '.')

The number of students in the Java class is 20 .
The number of students in the C++ class is 23 .
The number of students in the Python class is 29 .


In [22]:
for key in class_size.keys():
    print(key)

Java
C++
Python


### Sets

In [25]:
ls_a = ['a', 'b', 'a', np.pi, 36] 

In [26]:
st_a = set(ls_a)
st_a

{3.141592653589793, 36, 'a', 'b'}

In [27]:
st_b = {'d', 36, 'Holy Grail', np.pi}
st_b

{3.141592653589793, 36, 'Holy Grail', 'd'}

In [28]:
# union
st_a | st_b

{3.141592653589793, 36, 'Holy Grail', 'a', 'b', 'd'}

In [29]:
# intersection
st_a & st_b

{3.141592653589793, 36}

In [31]:
# difference
st_a - st_b

{'a', 'b'}

In [32]:
# difference
st_b - st_a

{'Holy Grail', 'd'}

### JSON

In [33]:
import json
JSON_string = '{"class 0" : "intro", "class 1" : "coding basics", "class 2": "basic structures"}'
type(JSON_string)

str

In [34]:
class_dict = json.loads(JSON_string)
type(class_dict)
class_dict

{'class 0': 'intro', 'class 1': 'coding basics', 'class 2': 'basic structures'}

In [35]:
type(class_dict)

dict

In [36]:
class_dict.keys()

dict_keys(['class 0', 'class 1', 'class 2'])

In [37]:
class_dict.values()

dict_values(['intro', 'coding basics', 'basic structures'])

In [38]:
type(class_dict)

dict

### Modules

In [40]:
import math

In [41]:
math.cos(2*math.pi)

1.0

In [42]:
from math import *
cos(pi)

-1.0

In [44]:
from numpy import ceil, floor

In [46]:
print(ceil(5.5))
print(floor(5.5))

6.0
5.0


In [47]:
import pandas as pd

<ipython-input-47-7dd3504c366f>:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [49]:
data = [1,2,3,4]

series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
dtype: int64


In [50]:
import sample_module as mymod

<class 'ModuleNotFoundError'>: No module named 'sample_module'

In [51]:
mymod.print_hello('Monty Python')

<class 'NameError'>: name 'mymod' is not defined